Repository naw-db/naw-db.github.io, pull requests merged in 2023-05, with the labels that each got.

#56 feat: Jalen Green, rank 3 to 4 = Andrew Wiggins
  content/data/players.csv
Labels: data

#58 Added Announcements section.
  content/data/announcements.csv
  content/sections/hero/hero.json
  src/components/sections/AnnouncementsSection.js
  src/pages/index.js
  src/pages/tips.js
Labels: enhancement

#60 Ordered players first by last name then by first name.
  src/components/players/PlayersComparisonChart.js
  src/components/players/PlayersTable.js
Labels: enhancement

#55 Added new entries and correction.
  content/data/pants.csv
  content/data/players.csv
  content/data/shirts.csv
  content/data/sneakers.csv
  src/components/credits/CreditsSection.js
Labels: data

#63 Added drop zone rewards.
  content/data/announcements.csv
  content/data/balls.csv
  content/data/daily_arena_tournament_rewards.csv
  content/data/daily_arena_tournament_rewards_by_team_level.csv
  content/data/drop_zone_rewards.csv
  content/data/encounter_rewards.csv
  content/data/event_tournament_history.csv
  content/data/eyewear.csv
  content/data/headwear.csv
  content/data/milestone_rewards.csv
  content/data/one_on_one_rewards.csv
  content/data/pants.csv
  content/data/player_level_requirements.csv
  content/data/players.csv
  content/data/practice_court_rewards.csv
  content/data/referral_rewards.csv
  content/data/rule_the_court_rewards.csv
  content/data/shirts.csv
  content/data/sneakers.csv
  content/data/socks.csv
  content/data/team_level_tips.csv
  content/data/weekly_arena_tournament_rewards.csv
  src/components/rewards/DropZoneRewardsTable.js
  src/components/rewards/RewardsTabs.js
  src/components/rewards/TeamLevelRewardsTable.js
  src/pages/rewards.js
Labels: enhancement, data

#66 Added a note for abbreviations at the top of the team level tips table and made wording in team level tips more consistent.
  content/data/team_level_tips.csv
  src/pages/tips.js
Labels: data

#79 Changed src and data package names. Also added e2e tests for ComparePlayers.
  .gitignore
  README.dev.md
  cypress.config.ts
  cypress/e2e/compare-players.cy.ts
  cypress/e2e/explore-players.cy.ts
  cypress/support/commands.ts
  cypress/support/index.d.ts
  src/components/common/Table.tsx
  src/components/events/EventTournamentHistoryTable.tsx
  src/components/gear/BallsTable.tsx
  src/components/gear/EyewearTable.tsx
  src/components/gear/GearTabs.tsx
  src/components/gear/HeadwearTable.tsx
  src/components/gear/PantsTable.tsx
  src/components/gear/ShirtsTable.tsx
  src/components/gear/SneakersTable.tsx
  src/components/gear/SocksTable.tsx
  src/components/players/PlayerLevelsRequirementsTable.tsx
  src/components/players/PlayerStats.tsx
  src/components/players/PlayersComparisonChart.tsx
  src/components/players/PlayersTable.tsx
  src/components/rewards/ArenaTournamentRewardsTable.tsx
  src/components/rewards/DropZoneRewardsTable.tsx
  src/components/rewards/EncounterRewardsTable.tsx
  src/components/rewards/MilestoneRewardsTable.tsx
  src/components/rewards/OneOnOneRewardsTable.tsx
  src/components/rewards/PracticeCourtRewardsTable.tsx
  src/components/rewards/ReferralRewardsTable.tsx
  src/components/rewards/RewardsTabs.tsx
  src/components/rewards/RuleTheCourtRewardsTable.tsx
  src/components/rewards/TeamLevelRewardsTable.tsx
  src/components/tips/TeamLevelTipsTable.tsx
  src/module.d.ts
  src/pages/compare-players.tsx
  src/pages/credits.tsx
  src/pages/explore-players.tsx
  src/pages/gear.tsx
  src/pages/index.tsx
  src/pages/more.tsx
  src/pages/rewards.tsx
  src/pages/tips.tsx
  tsconfig.json
Labels: enhancement

#80 Added anchor icons to Tips and More.
  src/components/common/AnchoredSection.tsx
  src/components/common/Tab.tsx
  src/components/gear/GearTabs.tsx
  src/components/players/PlayersComparisonChart.tsx
  src/components/rewards/RewardsTabs.tsx
  src/pages/more.tsx
  src/pages/tips.tsx
Labels: enhancement

#81 Added tests for Gear tabs.
  .github/workflows/pr_dry_run.yml
  cypress.config.ts
  cypress/e2e/compare-players.cy.ts
  cypress/e2e/explore-players.cy.ts
  cypress/e2e/gear-balls.cy.ts
  cypress/e2e/gear-eyewear.cy.ts
  cypress/e2e/gear-headwear.cy.ts
  cypress/e2e/gear-pants.cy.ts
  cypress/e2e/gear-shirts.cy.ts
  cypress/e2e/gear-sneakers.cy.ts
  cypress/e2e/gear-socks.cy.ts
  cypress/support/commands.ts
  cypress/support/index.d.ts
  src/components/gear/BallsTable.tsx
  src/components/gear/EyewearTable.tsx
  src/components/gear/HeadwearTable.tsx
  src/components/gear/PantsTable.tsx
  src/components/gear/ShirtsTable.tsx
  src/components/gear/SneakersTable.tsx
  src/components/gear/SocksTable.tsx
  src/pages/more.tsx
  src/pages/tips.tsx
Labels: enhancement

#82 Added tests for rewards page, tips page and more page.
  cypress/e2e/explore-players.cy.ts
  cypress/e2e/gear-balls.cy.ts
  cypress/e2e/gear-eyewear.cy.ts
  cypress/e2e/gear-headwear.cy.ts
  cypress/e2e/gear-pants.cy.ts
  cypress/e2e/gear-shirts.cy.ts
  cypress/e2e/gear-sneakers.cy.ts
  cypress/e2e/gear-socks.cy.ts
  cypress/e2e/more.cy.ts
  cypress/e2e/rewards-arena-tournament.cy.ts
  cypress/e2e/rewards-drop-zone.cy.ts
  cypress/e2e/rewards-encounter.cy.ts
  cypress/e2e/rewards-milestones.cy.ts
  cypress/e2e/rewards-one-on-one.cy.ts
  cypress/e2e/rewards-practice-court.cy.ts
  cypress/e2e/rewards-referral.cy.ts
  cypress/e2e/rewards-rule-the-court.cy.ts
  cypress/e2e/rewards-team-level.cy.ts
  cypress/e2e/tips.cy.ts
  cypress/support/commands.ts
  cypress/support/index.d.ts
Labels: enhancement

#83 Support up to four players to be compared in ComparePlayers.
  .gitignore
  content/data/announcements.csv
  cypress/e2e/compare-players.cy.ts
  cypress/support/commands.ts
  cypress/support/index.d.ts
  src/components/common/Defaults.ts
  src/components/gear/GearTabs.tsx
  src/components/players/PlayersComparisonChart.tsx
  src/components/players/PlayersTable.tsx
  src/components/rewards/RewardsTabs.tsx
  src/pages/compare-players.tsx
  src/pages/more.tsx
  src/pages/tips.tsx
Labels: enhancement

#84 Supported multi select for Division in ExplorePlayers.
  content/data/announcements.csv
  cypress/e2e/explore-players.cy.ts
  src/components/players/PlayersTable.tsx
Labels: enhancement

#85 Added multi select support to Position column in ExplorePlayers.
  content/data/announcements.csv
  cypress/e2e/explore-players.cy.ts
  cypress/e2e/gear/balls.cy.ts
  cypress/e2e/gear/eyewear.cy.ts
  cypress/e2e/gear/headwear.cy.ts
  cypress/e2e/gear/pants.cy.ts
  cypress/e2e/gear/shirts.cy.ts
  cypress/e2e/gear/sneakers.cy.ts
  cypress/e2e/gear/socks.cy.ts
  cypress/e2e/rewards/arena-tournament.cy.ts
  cypress/e2e/rewards/drop-zone.cy.ts
  cypress/e2e/rewards/encounter.cy.ts
  cypress/e2e/rewards/milestones.cy.ts
  cypress/e2e/rewards/one-on-one.cy.ts
  cypress/e2e/rewards/practice-court.cy.ts
  cypress/e2e/rewards/referral.cy.ts
  cypress/e2e/rewards/rule-the-court.cy.ts
  cypress/e2e/rewards/team-level.cy.ts
  src/components/common/Table.tsx
  src/components/players/PlayersTable.tsx
Labels: enhancement

#86 Data updates.
  content/data/pants.csv
  content/data/shirts.csv
  content/data/sneakers.csv
  src/components/players/PlayersComparisonChart.tsx
Labels: data

#87 Simplified announcements data and included validate-data in some yarn scripts.
  content/data/announcements.csv
  package.json
  src/components/sections/AnnouncementsSection.tsx
  src/pages/index.tsx
Labels: enhancement

#88 Added more tips and anchor link support upon page load.
  content/md/tips/arena_tournaments.md
  content/md/tips/boosts.md
  content/md/tips/cash.md
  content/md/tips/energy.md
  content/md/tips/gear.md
  content/md/tips/milestones.md
  content/md/tips/players.md
  content/md/tips/referrals.md
  content/md/tips/rule_the_court.md
  content/md/tips/team_levels.md
  cypress/e2e/more.cy.ts
  cypress/e2e/tips.cy.ts
  cypress/support/commands.ts
  cypress/support/index.d.ts
  src/components/common/AnchorScroller.tsx
  src/components/common/AnchoredMarkdownSection.tsx
  src/components/common/AnchoredSection.tsx
  src/pages/compare-players.tsx
  src/pages/credits.tsx
  src/pages/explore-players.tsx
  src/pages/gear.tsx
  src/pages/more.tsx
  src/pages/rewards.tsx
  src/pages/tips.tsx
Labels: enhancement

#93 Bug fix: allow same player to be compared.
  cypress/e2e/compare-players.cy.ts
  src/components/players/PlayersComparisonChart.tsx
Labels: bug, enhancement

#95 Increase page width in desktop view.
  src/components/events/EventTournamentHistoryTable.tsx
  src/components/gear/BallsTable.tsx
  src/components/gear/EyewearTable.tsx
  src/components/gear/HeadwearTable.tsx
  src/components/gear/PantsTable.tsx
  src/components/gear/ShirtsTable.tsx
  src/components/gear/SneakersTable.tsx
  src/components/gear/SocksTable.tsx
  src/components/players/PlayerLevelsRequirementsTable.tsx
  src/components/rewards/ArenaTournamentRewardsTable.tsx
  src/components/rewards/DropZoneRewardsTable.tsx
  src/components/rewards/EncounterRewardsTable.tsx
  src/components/rewards/MilestoneRewardsTable.tsx
  src/components/rewards/OneOnOneRewardsTable.tsx
  src/components/rewards/PracticeCourtRewardsTable.tsx
  src/components/rewards/ReferralRewardsTable.tsx
  src/components/rewards/RuleTheCourtRewardsTable.tsx
  src/components/rewards/TeamLevelRewardsTable.tsx
  src/components/tips/TeamLevelTipsTable.tsx
  src/gatsby-theme-portfolio-minimal/globalStyles/global.css
Labels: enhancement

#98 Added multi-select support to Type column in ExplorePlayers.
  cypress/e2e/explore-players.cy.ts
  src/components/players/PlayersTable.tsx
Labels: enhancement

#99 Changed Credits page to use Markdown, and removed dependency 'react-code-blocks'.
  content/md/credits/data.md
  content/md/credits/other_contributors.md
  content/md/credits/web_dev.md
  package.json
  src/components/credits/CreditsSection.tsx
  src/pages/credits.tsx
  src/pages/explore-players.tsx
  src/pages/gear.tsx
  src/pages/more.tsx
  src/pages/rewards.tsx
  src/pages/tips.tsx
  yarn.lock
Labels: enhancement

#96 Data updates.
  content/data/pants.csv
  content/data/shirts.csv
  content/data/sneakers.csv
Labels: data

#106 Added overall to ComparePlayers.
  cypress/support/commands.ts
  src/components/players/PlayerStats.tsx
  src/components/players/PlayersComparisonChart.tsx
Labels: enhancement
